### ISSUE TITLE
Breaks scrapper

### ISSUE THREAD

**Issue by grifenpierre** [jiejasonliu/ror2-reconsume#4]
With the last update (1.2.3), scrappers fails to drop any items. They grind it, but no scraps comes out.

**Comment by jiejasonliu** [comment]
thanks for the report! i'll look into this in the next couple of days

**Comment by jiejasonliu** [comment]
fix is implemented with #5, it should also be live on [Thunderstore](https://thunderstore.io/package/jiejasonliu/Reconsume/).

**Comment by grifenpierre** [comment]
it has indeed been fixed
