### ISSUE TITLE
Add rusted key?

### ISSUE THREAD

**Issue by Tymmey** [jiejasonliu/ror2-reconsume#6]
Hi There 📦 
can you also add rusted key to be reconsumable? 

best regards! and thanks for the mod!

**Comment by jiejasonliu** [comment]
thanks for the suggestion! 

so, i'm a little concerned about the balancing here:
* rusted keys aren't consumable items by nature, they disappear immediately after using it
* lockboxes also spawn according to how many players have a key -- being able to reconsume this item would imply that getting one key is all you'll ever need for the rest of the run

**Comment by Tymmey** [comment]
hmnm yeah, now as you said it, you're probably right.
last time i was just a bit wondered after seeing a used rust key in inventory, last time was so long ago :D

but maybe you could make it, to disappear completely?

**Comment by jiejasonliu** [comment]
> but maybe you could make it, to disappear completely?

can you clarify what you mean by _disappear completely?_ 
after the Anniversary Update, rusted keys already disappear after use

**Comment by Tymmey** [comment]
yeah, my bad! it seems to be a mod that shows used rusted keys for me ... 
you can ignore this :D
